import Head from "next/head";
import { ReactElement } from "react";
import Banner from "@/components/home/banner";
import Layout from "@/pages/layout";

export default function Home() {
  return (
    <>
      <Head>
        <title>판다마켓</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='bg-blue-200'>
        <Banner top />
        <Banner bottom />
      </main>
    </>
  );
}

Home.getLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>;
};
