import Head from 'next/head';

function Home() {
  return (
    <>
      <Head>
        <title>판다마켓</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <h1>Home Page</h1>
    </>
  );
}

export default Home;
